CREATE DATABASE ANTONIO;
USE ANTONIO;

CREATE TABLE users(
    iduser INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(45) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL
) ENGINE=INNODB;

CREATE TABLE numbers(
    idnumber INT PRIMARY KEY AUTO_INCREMENT,
    date DATETIME NOT NULL,
    description TEXT NULL,
    iduser_user INT NOT NULL,
    CONSTRAINT fk_user_number
    FOREIGN KEY (iduser_user) REFERENCES users(iduser)
    ON DELETE CASCADE
) ENGINE=INNODB;